services:
  - type: web
    name: n8n-trading-project
    runtime: docker
    image:
      url: docker.io/n8nio/n8n:latest
    plan: free
    envVars:
      - key: N8N_HOST
        value: n8n-trading-project.onrender.com
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        value: https://n8n-trading-project.onrender.com/
      - key: N8N_EDITOR_BASE_URL
        value: https://n8n-trading-project.onrender.com/
      - key: GENERIC_TIMEZONE
        value: Africa/Algiers
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        value: db.fnxknbgrfocewvhmgnfl.supabase.co
      - key: DB_POSTGRESDB_PORT
        value: 5432
      - key: DB_POSTGRESDB_DATABASE
        value: postgres
      - key: DB_POSTGRESDB_USER
        value: postgres
      - key: DB_POSTGRESDB_PASSWORD
        sync: false
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: youcef
      - key: N8N_BASIC_AUTH_PASSWORD
        sync: false
